import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { IRS_RATE_PER_MILE } from '../constants/constants'; // FIX: shared constant so rate stays in sync

// Build trip rows as a plain function to avoid nested template literal conflicts
function buildTripRows(trips) {
  return trips.map((trip) => {
    const tripDate = trip.timestamp?.toDate ? trip.timestamp.toDate() : new Date();
    const value = (parseFloat(trip.miles || 0) * IRS_RATE_PER_MILE).toFixed(2);
    const date = tripDate.toLocaleDateString();
    const miles = trip.miles || 0;
    const type = trip.type || 'Business';
    return '<tr><td>' + date + '</td><td>' + miles + ' mi</td><td>' + type + '</td><td>$' + value + '</td></tr>';
  }).join('');
}

export const generateTaxReport = async (trips, totalDeduction, year) => {
  const html = `
    <html>
      <head>
        <style>
          body { font-family: 'Helvetica', sans-serif; padding: 20px; }
          h1 { color: #333; text-align: center; }
          .summary { background: #f4f4f4; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
          .total { font-size: 24px; font-weight: bold; color: #2e7d32; }
          table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          th { background: #333; color: white; padding: 10px; text-align: left; }
          td { border-bottom: 1px solid #ddd; padding: 10px; }
          tr:nth-child(even) { background-color: #f9f9f9; }
        </style>
      </head>
      <body>
        <h1>DriverPro Tax Report (${year})</h1>
        
        <div class="summary">
          <p>Total Trips: <strong>${trips.length}</strong></p>
          <p>IRS Mileage Rate: <strong>$${IRS_RATE_PER_MILE.toFixed(2)}/mile</strong></p>
          <p>Total Potential Deduction:</p>
          <p class="total">$${totalDeduction.toFixed(2)}</p>
        </div>

        <table>
          <thead>
            <tr>
              <th>Date</th>
              <th>Distance</th>
              <th>Purpose</th>
              <th>Value</th>
            </tr>
          </thead>
          <tbody>
            ${buildTripRows(trips)}
          </tbody>
        </table>
        
        <p style="text-align: center; margin-top: 50px; color: #888;">
          Generated by DriverPro - Keep this for your tax records.
        </p>
      </body>
    </html>
  `;

  // Errors bubble up to WalletScreen which handles the user-facing alert
  const { uri } = await Print.printToFileAsync({ html });
  await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
};