import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

export const generateTaxReport = async (trips, totalDeduction, year) => {
  // 1. Create the HTML Template
  // This looks like a real document with a header and table
  const html = `
    <html>
      <head>
        <style>
          body { font-family: 'Helvetica', sans-serif; padding: 20px; }
          h1 { color: #333; text-align: center; }
          .summary { background: #f4f4f4; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
          .total { font-size: 24px; font-weight: bold; color: #2e7d32; }
          table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          th { background: #333; color: white; padding: 10px; text-align: left; }
          td { border-bottom: 1px solid #ddd; padding: 10px; }
          tr:nth-child(even) { background-color: #f9f9f9; }
        </style>
      </head>
      <body>
        <h1>DriverPro 🚗 Tax Report (${year})</h1>
        
        <div class="summary">
          <p>Total Trips: <strong>${trips.length}</strong></p>
          <p>Total Potential Deduction:</p>
          <p class="total">$${totalDeduction.toFixed(2)}</p>
        </div>

        <table>
          <thead>
            <tr>
              <th>Date</th>
              <th>Distance</th>
              <th>Purpose</th>
              <th>Value</th>
            </tr>
          </thead>
          <tbody>
            ${trips.map(trip => `
              <tr>
                <td>${new Date(trip.date.seconds * 1000).toLocaleDateString()}</td>
                <td>${trip.distance.toFixed(2)} mi</td>
                <td>${trip.type || 'Business'}</td>
                <td>$${(trip.distance * 0.67).toFixed(2)}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
        
        <p style="text-align: center; margin-top: 50px; color: #888;">
          Generated by DriverPro - Keep this for your tax records.
        </p>
      </body>
    </html>
  `;

  // 2. Generate the PDF
  try {
    const { uri } = await Print.printToFileAsync({ html });
    console.log('PDF Generated at:', uri);

    // 3. Share/Save the File
    await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
  } catch (error) {
    console.error("Error generating PDF:", error);
  }
};